language: node_js
node_js:
  - 11
script:
  - "npm test"
    #after_success:
    #  - "npm run coveralls"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
      - g++-4.9
