apipath: /index.php?page=api&action=public
timeout:
  api: 10000
  stratum: 1000
pools:
  -
    name: LA Bitzeny Pool
    shortname: LA Pool
    id: lapool
    url: https://lapool.me/bitzeny
    alert_enabled: true
    stratum:
      host: jp.lapool.me
      port: 3014
  -
    name: zeny MDpool
    shortname: MDpool
    id: mdpool
    url: https://zeny.mdpool.info
    alert_enabled: false
    stratum:
      host: zeny.mdpool.info
      port: 6969
  -
    name: zeny MDpool(new)
    shortname: MDpool(new)
    id: mdnew
    url: https://n-zeny.mdpool.info
    alert_enabled: false
    stratum:
      host: mining-zeny.mdpool.info
      port: 6962
  -
    name: うさぎコイン発掘所
    shortname: うさぎコイン
    id: bunny
    url: https://bunnymining.work/bitzeny
    alert_enabled: true
    stratum:
      host: bunnymining.work
      port: 19333
  -
    name: みそスープール
    id: soupmiso
    url: https://soup.misosi.ru
    alert_enabled: true
    stratum:
      host: stratum.misosi.ru
      port: 16001
  -
    name: 大人の自由研究
    id: otonajiyuu
    url: https://ukkey3.space/bitzeny
    alert_enabled: true
    stratum:
      host: ukkey3.space
      port: 3333
  -
    name: 寛 永 通 宝
    shortname: 寛永通宝
    id: kannei
    url: https://portal.bitzenypool.work
    alert_enabled: true
    stratum:
      host: bitzenypool.work
      port: 19666
  -
    name: BitZeny選民プール
    shortname: 選民プール
    id: senmin
    url: https://zny.arunyastyle.com
    alert_enabled: true
    stratum:
      host: zny.arunyastyle.com
      port: 19666
  -
    name: wmapool bitzeny(β)
    shortname: wmapool
    id: wmapool
    url: https://www.wmapool.net
    alert_enabled: true
    stratum:
      host: wmapool.net
      port: 19667
  -
    name: みずたまり【テスト稼働中】
    shortname: みずたまり
    id: mizutamari
    url: https://bitzeny.mizutamari.work
    alert_enabled: true
    stratum:
      host: bitzeny-m.mizutamari.work
      port: 19702
  -
    name: Knyacki pool
    shortname: Knyacki
    id: knyacki
    url: https://pool.knyacki.xyz
    alert_enabled: true
    stratum:
      host: pool.knyacki.xyz
      port: 8888
  -
    name: bitzeny発掘場　コインラッシュ
    shortname: コインラッシュ
    id: coinrush
    url: http://coinrush.work
    alert_enabled: true
    stratum:
      host: coinrush.work
      port: 19333
  -
    name: とある鯖管理人が運営するBitzeny採掘所
    shortname: とある鯖管
    id: sabakan
    url: https://pool1.znymining.net
    alert_enabled: true
    stratum:
      host: pool1.znymining.net
      port: 19666
  -
    name: 銭プール（ZNY）
    shortname: 銭プール
    id: zenypool
    url: https://zny.coiner.site
    alert_enabled: true
    stratum:
      host: zny.coiner.site
      port: 9252
  -
    name: Hoge Pool - Bitzeny Mining Pool
    shortname: Hoge Pool
    id: hogepool
    url: https://hogepool.net
    alert_enabled: true
    stratum:
      host: stratum01.hogepool.net
      port: 3333
  -
    name: powerpool for BitZeny
    shortname: powerpool
    id: powerpool
    url: https://zny.powerpool.jp
    alert_enabled: true
    stratum:
      host: m.powerpool.jp
      port: 3333
