apiPath:
  mpos: /index.php?page=api&action=public
  nomp: /api/stats
  yiimp: /api
timeout:
  api: 10000
  stratum: 1000
hashPowerWarn: 40
maxRetry: 4
cron:
  check: 5
  tweet: 3
pools:
  -
    name: LA Bitzeny Pool
    shortname: LA Pool
    id: lapool
    url: https://lapool.me/bitzeny
    type: mpos
    alert_disabled: false
    stratum:
      host: jp.lapool.me
      port: 3014
  -
    name: zeny MDpool(new)
    shortname: MDpool(new)
    id: mdnew
    url: https://n-zeny.mdpool.info
    type: mpos
    stratum:
      host: mining-zeny.mdpool.info
      port: 6962
  -
    name: うさぎコイン発掘所
    shortname: うさぎコイン
    id: bunny
    url: https://bunnymining.work/bitzeny
    type: mpos
    stratum:
      host: bitzeny.bunnymining.work
      port: 19333
  -
    name: 大人の自由研究
    id: otonajiyuu
    url: https://ukkey3.space/bitzeny
    type: mpos
    stratum:
      host: ukkey3.space
      port: 3333
  -
    name: とある鯖管理人が運営するBitzeny採掘所
    shortname: とある鯖管
    id: sabakan
    url: https://pool1.znymining.net
    type: mpos
    stratum:
      host: pool1.znymining.net
      port: 19666
  -
    name: なんかBitZenyっていうイケハヤさん押し草コインのマイニングプール
    shortname: イケハヤさん押し草コイン
    id: ikehaya
    url: https://www.zenymypool.work
    type: mpos
    stratum:
      host: zenymypool.work
      port: 19666
  -
    name: mofumofu.me
    id: mofumofu
    url: https://zny.mofumofu.me
    type: nomp
    stratum:
      host: zny.mofumofu.me
      port: 3333
  -
    name: 人のプール
    id: hitonopool
    url: http://mining.zinntikumugai.xyz
    type: nomp
    stratum:
      host: stratum.zinntikumugai.xyz
      port: 4001
  -
    name: macyan.net
    id: macyan
    url: http://macyan.net:8080
    type: nomp
    stratum:
      host: macyan.net
      port: 3032
  -
    name: SEMI-POOL
    id: semi
    url: https://zny.semipool.net
    type: nomp
    stratum:
      host: zny.semipool.net
      port: 3333
  -
    name: Fi Pool
    id: fipool
    url: 153.126.177.24/bitzeny
    type: mpos
    stratum:
      host: 153.126.177.24
      port: 19000
  -
    name: pecadol pool
    id: pecadol
    url: https://pool.pecadol.xyz
    type: yiimp
    stratum:
      host: pool.pecadol.xyz
      port: 6383
  -
    name: Cryptogrinder
    id: grinder
    url: https://cryptogrinder.com
    type: nomp
    stratum:
      host: cryptogrinder.com
      port: 9002
  -
    name: Zergpool
    id: zergpool
    url: https://zergpool.com
    api_url: http://api.zergpool.com:8080/api/status
    type: yiimp
    stratum:
      host: yescryptR8.mine.zergpool.com
      port: 6323
  -
    name: LeyWa Mining Pool
    id: leywa
    url: https://leywapool.com
    type: yiimp
    stratum:
      host: leywapool.com
      port: 6243
