apiPath:
  mpos: /index.php?page=api&action=public
  nomp: /api/stats
timeout:
  api: 10000
  stratum: 1000
hashPowerWarn: 40
maxRetry: 4
pools:
  -
    name: LA Bitzeny Pool
    shortname: LA Pool
    id: lapool
    url: https://lapool.me/bitzeny
    type: mpos
    stratum:
      host: jp.lapool.me
      port: 3014
  -
    name: zeny MDpool(new)
    shortname: MDpool(new)
    id: mdnew
    url: https://n-zeny.mdpool.info
    type: mpos
    stratum:
      host: mining-zeny.mdpool.info
      port: 6962
  -
    name: うさぎコイン発掘所
    shortname: うさぎコイン
    id: bunny
    url: https://bunnymining.work/bitzeny
    type: mpos
    stratum:
      host: bitzeny.bunnymining.work
      port: 19333
  -
    name: みそスープール
    id: soupmiso
    url: https://soup.misosi.ru
    type: mpos
    stratum:
      host: stratum.misosi.ru
      port: 16001
  -
    name: 大人の自由研究
    id: otonajiyuu
    url: https://ukkey3.space/bitzeny
    type: mpos
    stratum:
      host: ukkey3.space
      port: 3333
#  -
#    name: 寛 永 通 宝
#    shortname: 寛永通宝
#    id: kannei
#    url: https://portal.bitzenypool.work
#    type: mpos
#    stratum:
#      host: bitzenypool.work
#      port: 19666
  -
    name: みずたまり（bitzenyマイニングプール）
    shortname: みずたまり
    id: mizutamari
    url: https://bitzeny.mizutamari.work
    type: mpos
    stratum:
      host: bitzeny-m.mizutamari.work
      port: 19702
  -
    name: とある鯖管理人が運営するBitzeny採掘所
    shortname: とある鯖管
    id: sabakan
    url: https://pool1.znymining.net
    type: mpos
    stratum:
      host: pool1.znymining.net
      port: 19666
  -
    name: 銭プール（ZNY）
    shortname: 銭プール
    id: zenypool
    url: https://zny.coiner.site
    type: mpos
    stratum:
      host: zny.coiner.site
      port: 19666
  -
    name: powerpool for BitZeny
    shortname: powerpool
    id: powerpool
    url: https://zny.powerpool.jp
    type: mpos
    stratum:
      host: m.powerpool.jp
      port: 3333
  -
    name: Hoge Pool - Bitzeny Mining Pool
    shortname: Hoge Pool
    id: hogepool
    url: https://hogepool.net
    type: mpos
    stratum:
      host: stratum01.hogepool.net
      port: 3333
  -
    name: 俺のプール＠東京店
    id: orenopool
    url: https://bitzeny2.mypool.tokyo
    type: nomp
    stratum:
      host: bitzeny2.mypool.tokyo
      port: 5332
  -
    name: ココアプール
    id: cocoa
    url: https://www.cocoapool.net
    type: mpos
    stratum:
      host: s.cocoapool.net
      port: 14943
  -
    name: Daddy-Pool
    id: daddy
    url: http://zny.daddy-pool.work
    type: nomp
    stratum:
      host: zny.daddy-pool.work
      port: 15021
  -
    name: Bluepool
    id: bluepool
    url: https://bitzeny.bluepool.info
    type: nomp
    stratum:
      host: bitzeny.bluepool.info
      port: 9999
  -
    name: kruptos
    id: kruptos
    url: http://mining.bit-univ.jp
    type: nomp
    stratum:
      host: mining.bit-univ.jp
      port: 43330
  -
    name: ZenyPool
    id: zenypoolcom
    url: https://hp.zenypool.com
    type: mpos
    stratum:
      host: hp.zenypool.com
      port: 7777
  -
    name: ぷりぷりぷーる（bitzeny）
    shortname: ぷりぷりぷーる
    id: puripuri
    url: https://puripuripool.tk
    type: mpos
    stratum:
      host: puripuripool.tk
      port: 18001
  -
    name: なんかBitZenyっていうイケハヤさん押し草コインのマイニングプール
    shortname: イケハヤさん押し草コイン
    id: ikehaya
    url: https://www.zenymypool.work
    type: mpos
    stratum:
      host: zenymypool.work
      port: 19666
  -
    name: '禅風 : A Bitzeny Mining Pool'
    shortname: 禅風
    id: zenpoo
    url: https://zenpoo.nyem.net
    type: mpos
    stratum:
      host: zenpoo.nyem.net
      port: 19666
  -
    name: Auriga BitZeny Pool
    shortname: Auriga
    id: auriga
    url: https://zeny.auri.ga
    type: mpos
    stratum:
      host: zeny.auri.ga
      port: 3330
  -
    name: mofumofu.me
    id: mofumofu
    url: https://zny.mofumofu.me
    type: nomp
    stratum:
      host: zny.mofumofu.me
      port: 3333
  -
    name: 人のプール
    id: hitonopool
    url: http://mining.zinntikumugai.xyz
    type: nomp
    stratum:
      host: stratum.zinntikumugai.xyz
      port: 4001
  -
    name: 採掘だよ！全員集合！
    id: letsmine
    url: http://letsminezny.orz.hm:8080
    type: nomp
    stratum:
      host: letsminezny.orz.hm
      port: 1234
  -
    name: Exampool
    id: exampool
    url: https://zny.xmpool.net
    type: mpos
    stratum:
      host: fipool.com
      port: 19000
  -
    name: NOMP.ZNY.POWERPOOL
    id: nomppower
    url: https://nomp.zny.powerpool.jp
    type: nomp
    stratum:
      host: nomp.zny.powerpool.jp
      port: 16030

