apiPath:
  mpos: /index.php?page=api&action=public
  nomp: /api/stats
  yiimp: /api
timeout:
  api: 10000
  stratum: 1000
hashPowerWarn: 40
maxRetry: 4
cron:
  check: 5
  tweet: 3
pools:
  -
    name: LA Bitzeny Pool
    shortname: LA Pool
    id: lapool
    url: https://lapool.me/bitzeny
    type: mpos
    stratum:
      host: jp.lapool.me
      port: 3014
  -
    name: zeny MDpool(new)
    shortname: MDpool(new)
    id: mdnew
    url: https://n-zeny.mdpool.info
    type: mpos
    stratum:
      host: mining-zeny.mdpool.info
      port: 6962
  -
    name: うさぎコイン発掘所
    shortname: うさぎコイン
    id: bunny
    url: https://bunnymining.work/bitzeny
    type: mpos
    message: （メンテナンス予定：4/18 14:00-20:00）
    message_summary: 4/18 20時までメンテ
    stratum:
      host: bitzeny.bunnymining.work
      port: 19333
  -
    name: 大人の自由研究
    id: otonajiyuu
    url: https://ukkey3.space/bitzeny
    type: mpos
    stratum:
      host: ukkey3.space
      port: 3333
#  -
#    name: 寛 永 通 宝
#    shortname: 寛永通宝
#    id: kannei
#    url: https://portal.bitzenypool.work
#    type: mpos
#    stratum:
#      host: bitzenypool.work
#      port: 19666
  -
    name: みずたまり（bitzenyマイニングプール）
    shortname: みずたまり
    id: mizutamari
    url: https://bitzeny.mizutamari.work
    type: mpos
    stratum:
      host: bitzeny-m.mizutamari.work
      port: 19702
  -
    name: とある鯖管理人が運営するBitzeny採掘所
    shortname: とある鯖管
    id: sabakan
    url: https://pool1.znymining.net
    type: mpos
    stratum:
      host: pool1.znymining.net
      port: 19666
  -
    name: powerpool for BitZeny
    shortname: powerpool
    id: powerpool
    url: https://zny.powerpool.jp
    type: mpos
    stratum:
      host: m.powerpool.jp
      port: 3333
  -
    name: Hoge Pool - Bitzeny Mining Pool
    shortname: Hoge Pool
    id: hogepool
    url: https://hogepool.net
    type: mpos
    stratum:
      host: stratum01.hogepool.net
      port: 3333
  -
    name: ココアプール
    id: cocoa
    url: https://www.cocoapool.net
    type: mpos
    stratum:
      host: s.cocoapool.net
      port: 14943
  -
    name: Daddy-Pool
    id: daddy
    url: http://zny.daddy-pool.work
    type: nomp
    stratum:
      host: zny.daddy-pool.work
      port: 15021
  -
    name: なんかBitZenyっていうイケハヤさん押し草コインのマイニングプール
    shortname: イケハヤさん押し草コイン
    id: ikehaya
    url: https://www.zenymypool.work
    type: mpos
    stratum:
      host: zenymypool.work
      port: 19666
  -
    name: '禅風 : A Bitzeny Mining Pool'
    shortname: 禅風
    id: zenpoo
    url: https://zenpoo.nyem.net
    type: mpos
    stratum:
      host: zenpoo.nyem.net
      port: 19666
  -
    name: mofumofu.me
    id: mofumofu
    url: https://zny.mofumofu.me
    type: nomp
    stratum:
      host: zny.mofumofu.me
      port: 3333
  -
    name: 人のプール
    id: hitonopool
    url: http://mining.zinntikumugai.xyz
    type: nomp
    stratum:
      host: stratum.zinntikumugai.xyz
      port: 4001
  -
    name: 採掘だよ！全員集合！
    id: letsmine
    url: http://letsminezny.orz.hm
    type: nomp
    alert_disabled: true
    stratum:
      host: letsminezny.orz.hm
      port: 1234
  -
    name: NOMP.ZNY.POWERPOOL
    id: nomppower
    url: https://nomp.zny.powerpool.jp
    type: nomp
    stratum:
      host: nomp.zny.powerpool.jp
      port: 16030
  -
    name: みんなのプール
    id: minnano
    url: https://www.minnano-pool.work
    type: nomp
    stratum:
      host: stratum.minnano-pool.work
      port: 3030
  -
    name: macyan.net
    id: macyan
    url: http://macyan.net:8080
    type: nomp
    stratum:
      host: macyan.net
      port: 3032
  -
    name: SEMI-POOL
    id: semi
    url: https://zny.semi-pool.com
    type: nomp
    stratum:
      host: zny.semi-pool.com
      port: 3333
  -
    name: Fi Pool
    id: fipool
    url: https://fipool.com/bitzeny
    type: mpos
    stratum:
      host: fipool.com
      port: 19000
  -
    name: pecadol pool
    id: pecadol
    url: https://pool.pecadol.xyz
    type: yiimp
    stratum:
      host: pool.pecadol.xyz
      port: 6383
  -
    name: Cryptogrinder
    id: grinder
    url: https://cryptogrinder.com
    type: nomp
    stratum:
      host: cryptogrinder.com
      port: 9002
  -
    name: Zergpool
    id: zergpool
    url: https://zergpool.com
    api_url: http://api.zergpool.com:8080/api/status
    type: yiimp
    stratum:
      host: yescryptR8.mine.zergpool.com
      port: 6323
  -
    name: ZPOOL
    id: zpool
    url: https://www.zpool.ca
    type: yiimp
    stratum:
      host: yescryptR8.jp.mine.zpool.ca
      port: 6323

