apipath: /index.php?page=api&action=public
timeout:
  api: 10000
  stratum: 1000
hashPowerWarn: 40
pools:
  -
    name: LA Bitzeny Pool
    shortname: LA Pool
    id: lapool
    url: https://lapool.me/bitzeny
    stratum:
      host: jp.lapool.me
      port: 3014
  -
    name: zeny MDpool(new)
    shortname: MDpool(new)
    id: mdnew
    url: https://n-zeny.mdpool.info
    stratum:
      host: mining-zeny.mdpool.info
      port: 6962
  -
    name: うさぎコイン発掘所
    shortname: うさぎコイン
    id: bunny
    url: https://bunnymining.work/bitzeny
    stratum:
      host: bitzeny.bunnymining.work
      port: 19333
  -
    name: みそスープール
    id: soupmiso
    url: https://soup.misosi.ru
    stratum:
      host: stratum.misosi.ru
      port: 16001
  -
    name: 大人の自由研究
    id: otonajiyuu
    url: https://ukkey3.space/bitzeny
    stratum:
      host: ukkey3.space
      port: 3333
  -
    name: 寛 永 通 宝
    shortname: 寛永通宝
    id: kannei
    url: https://portal.bitzenypool.work
    stratum:
      host: bitzenypool.work
      port: 19666
  -
    name: BitZeny選民プール
    shortname: 選民プール
    id: senmin
    url: https://zny.arunyastyle.com
    stratum:
      host: zny.arunyastyle.com
      port: 19666
  -
    name: wmapool bitzeny(β)
    shortname: wmapool
    id: wmapool
    url: https://www.wmapool.net
    stratum:
      host: wmapool.net
      port: 19667
  -
    name: みずたまり（bitzenyマイニングプール）
    shortname: みずたまり
    id: mizutamari
    url: https://bitzeny.mizutamari.work
    stratum:
      host: bitzeny-m.mizutamari.work
      port: 19702
  -
    name: Knyacki pool
    shortname: Knyacki
    id: knyacki
    url: https://pool.knyacki.xyz
    stratum:
      host: pool.knyacki.xyz
      port: 8888
  -
    name: bitzeny発掘場　コインラッシュ
    shortname: コインラッシュ
    id: coinrush
    url: http://coinrush.work
    stratum:
      host: coinrush.work
      port: 19333
  -
    name: とある鯖管理人が運営するBitzeny採掘所
    shortname: とある鯖管
    id: sabakan
    url: https://pool1.znymining.net
    stratum:
      host: pool1.znymining.net
      port: 19666
  -
    name: 銭プール（ZNY）
    shortname: 銭プール
    id: zenypool
    url: https://zny.coiner.site
    stratum:
      host: zny.coiner.site
      port: 19666
  -
    name: powerpool for BitZeny
    shortname: powerpool
    id: powerpool
    url: https://zny.powerpool.jp
    stratum:
      host: m.powerpool.jp
      port: 3333
  -
    name: Hoge Pool - Bitzeny Mining Pool
    shortname: Hoge Pool
    id: hogepool
    url: https://hogepool.net
    stratum:
      host: stratum01.hogepool.net
      port: 3333
  -
    name: WPOOL
    id: wpool
    url: https://wpool.work
    apipath: /api/stats
    stratum:
      host: wpool.work
      port: 15021
  -
    name: 俺のプール
    id: orenopool
    url: https://bitzeny.mypool.tokyo
    stratum:
      host: bitzeny.mypool.tokyo
      port: 9334
  -
    name: ココアプール
    id: cocoa
    url: https://www.cocoapool.net
    stratum:
      host: s.cocoapool.net
      port: 14943
  -
    name: Daddy-Pool
    id: daddy
    url: http://daddy-pool.work
    apipath: /api/stats
    stratum:
      host: daddy-pool.work
      port: 15021
  -
    name: Bluepool
    id: bluepool
    url: https://bitzeny.bluepool.info
    apipath: /api/stats
    stratum:
      host: bitzeny.bluepool.info
      port: 9999
  -
    name: kruptos
    id: kruptos
    url: http://mining.bit-univ.jp
    apipath: /api/stats
    stratum:
      host: mining.bit-univ.jp
      port: 43330
  -
    name: ZenyPool
    id: zenypoolcom
    url: https://zenypool.com
    stratum:
      host: zenypool.com
      port: 4444
  -
    name: ぷりぷりぷーる（bitzeny）
    shortname: ぷりぷりぷーる
    id: puripuri
    url: https://puripuripool.tk
    stratum:
      host: puripuripool.tk
      port: 18001
  -
    name: Pool-chan
    id: poolchan
    url: https://pool-chan.me
    stratum:
      host: pool-chan.me
      port: 19001
  -
    name: bitzeny.work
    id: bitzenywork
    url: https://bitzeny.work
    stratum:
      host: bitzeny.work
      port: 3034
  -
    name: なんかBitZenyっていうイケハヤさん押し草コインのマイニングプール
    shortname: イケハヤさん押し草コイン
    id: ikehaya
    url: https://www.zenymypool.work
    stratum:
      host: zenymypool.work
      port: 19666
  -
    name: '禅風 : A Bitzeny Mining Pool'
    shortname: 禅風
    id: zenpoo
    url: https://zenpoo.nyem.net
    stratum:
      host: zenpoo.nyem.net
      port: 19666
  -
    name: Auriga BitZeny Pool
    shortname: Auriga
    id: auriga
    url: https://zeny.auri.ga
    stratum:
      host: zeny.auri.ga
      port: 3330
  -
    name: 庶民プール
    id: shomin
    url: https://nomp1.arunyastyle.com
    apipath: /api/stats
    stratum:
      host: nomp1.arunyastyle.com
      port: 46491
  -
    name: Fi Pool
    id: fipool
    url: https://fipool.com/bitzeny
    stratum:
      host: fipool.com
      port: 19000
  -
    name: mofumofu.me
    id: mofumofu
    url: https://zny.mofumofu.me
    apipath: /api/stats
    stratum:
      host: zny.mofumofu.me
      port: 3333
