apiPath:
  mpos: /index.php?page=api&action=public
  nomp: /api/stats
  yiimp: /api
timeout:
  api: 10000      # [ms]
  stratum: 1000   # [ms]
hashPowerWarn: 40 # [%]
maxRetry: 4
cron:
  check: 5 # [min]
  tweet: 3 # [hour]
pools:
  -
    name: Full Pool Name
    shortname: Pool Name  # [optional]
    id: pool              # set unique id please
    url: https://pool.url
    type: mpos            # 'mpos' or 'nomp'
    alert_disabled: false # [optional]
    stratum:
      host: stratum.pool.url
      port: 8888
